version: '3'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  ml_service:
    build: ./ml_service
    ports:
      - "8001:8001"
  backend:
    build: ./backend
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/jobscape
      - ML_SERVICE_URL=http://ml_service:8001
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - ml_service
  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
    depends_on:
      - backend
volumes:
  mongo_data:
